### ISSUE TITLE
Syncing error with 2.21c

### ISSUE THREAD

**Issue by martin3783** [ClusterM/hakchi2#788]
This never happened with previous versions before. And this even happens with a brand new SNES Mini and a brand new installation. Syncing games is impossible now. Please help. 

![hakchi2 error](https://user-images.githubusercontent.com/32790120/31573964-d4a51e26-b0c5-11e7-9dcb-bdac48f8a94f.png)

**Comment by Epzzz** [comment]
Same here, had no problems before update. Did also go back to original kernel without it helping.

**Comment by ClusterM** [comment]
Have you used previous version of hakchi2 before?

**Comment by pitbzury** [comment]
Got the same error here, I use 2.20 before and others with nes also.
this error occurs at the very end of the synchronize process while it says "uploading new config"
Did so far : flash original kernel to restart, then flash custom kernel

**Comment by ClusterM** [comment]
Is is portable version? Can you send me the whole hakchi2 folder?

**Comment by pitbzury** [comment]
yes  portable version, it is possible to send it right to github?

**Comment by ClusterM** [comment]
You can send it me on e-mail: clusterrr@clusterrr.com
Send it as is or or as link.

**Comment by pitbzury** [comment]
Done, thanks for your help

**Comment by ClusterM** [comment]
Weird.
Try 2.21d please.

**Comment by pitbzury** [comment]
Tried on 2.21d
sync process completed, but no custom games available when I turn on the snes, only 21 original. So I flash custom kernel again and I got a md5 checksum warning : 
I didn't continue
![image](https://user-images.githubusercontent.com/32793456/31576030-0223b5f6-b0c1-11e7-8dd0-0d757c5e2137.png)


update : flash custom kernel from 2.21d,  says that kernel is now installed. Able to sync custom games, , but when I load, still only 21 original game only available

**Comment by ClusterM** [comment]
Can you make NAND-C dump via kernel menu and send this file to me on clusterrr@clusterrr.com?

**Comment by martin3783** [comment]
Thank you ClusterM!

2.2.1d fixed the error message. However, games are still not showing up in the SNES main menu, even when Hakchi said it did the upload. 

I don't get it. I never had a problem like this with Hakchi and everything up until 2.21c, always worked fine. 

I'll send you the NAND-C dump.

**Comment by pitbzury** [comment]
done too.
Looks like we got the same issue, hoping there's something to do.
thanks again for your help

**Comment by ClusterM** [comment]
Fixed. Issue was because of garbage files left from very-very old version.
Please update to 2.0.21.51.
